import type { Candidate, Pitch } from "./types";

export const avatarPalette = [
  "amber",
  "navy",
  "forest",
  "clay",
  "slate",
  "plum",
] as const;

export const candidates: Candidate[] = [
  {
    id: "amara-osei",
    name: "Amara Osei",
    title: "Senior Product Designer",
    location: "Toronto, Canada",
    workStyle: ["remote", "hybrid"],
    yearsExperience: 8,
    headline: "Design systems and 0→1 product work for fintech and B2B SaaS.",
    bio: "I lead design on products people trust with their money. Over the last eight years I've built and scaled design systems at two Series B startups and shipped a banking app used by 400K people. I care most about the seams — the states between happy paths where products actually earn trust.",
    skills: [
      "Product Design",
      "Design Systems",
      "Figma",
      "User Research",
      "Prototyping",
      "Accessibility",
    ],
    preferredRoles: ["Senior Product Designer", "Design Lead", "Staff Designer"],
    compMin: 145000,
    compMax: 175000,
    compPeriod: "year",
    availability: "Available in 3 weeks",
    openToOffers: true,
    experience: [
      {
        role: "Senior Product Designer",
        company: "Ledgerline",
        period: "2021 — Present",
        description: "Owned design for core banking flows; rebuilt the design system used across 6 product squads.",
      },
      {
        role: "Product Designer",
        company: "Wayfare",
        period: "2018 — 2021",
        description: "First design hire; shipped the booking flow redesign that lifted conversion 22%.",
      },
    ],
    portfolio: [
      {
        title: "Ledgerline Design System",
        description: "A token-based system spanning web and native, documented for a 40-person eng org.",
        url: "https://example.com/work/ledgerline-ds",
      },
      {
        title: "Wayfare Checkout Rebuild",
        description: "Case study on cutting checkout drop-off through progressive disclosure.",
        url: "https://example.com/work/wayfare-checkout",
      },
    ],
    links: {
      linkedin: "https://linkedin.com/in/amaraosei",
      github: undefined,
      website: "https://amaraosei.design",
    },
    accent: "amber",
    pitchCount: 3,
  },
  {
    id: "daniel-kwon",
    name: "Daniel Kwon",
    title: "Staff Backend Engineer",
    location: "Austin, TX",
    workStyle: ["remote"],
    yearsExperience: 11,
    headline: "Distributed systems at scale. Ex-payments infra, now open to platform roles.",
    bio: "I've spent the last decade making sure money moves correctly and on time. Most recently I led the ledger rewrite at a payments company processing $2B/year. I like hard consistency problems and teams that write postmortems without blame.",
    skills: ["Go", "PostgreSQL", "Kafka", "Distributed Systems", "AWS", "gRPC"],
    preferredRoles: ["Staff Engineer", "Principal Engineer", "Backend Lead"],
    compMin: 190000,
    compMax: 230000,
    compPeriod: "year",
    availability: "Available in 6 weeks",
    openToOffers: true,
    experience: [
      {
        role: "Staff Engineer",
        company: "Northbeam Pay",
        period: "2019 — Present",
        description: "Led the double-entry ledger rewrite; zero reconciliation incidents since launch.",
      },
      {
        role: "Senior Backend Engineer",
        company: "Fetch Logistics",
        period: "2015 — 2019",
        description: "Built the routing engine that scaled from 10K to 2M deliveries/month.",
      },
    ],
    portfolio: [
      {
        title: "Ledger Rewrite Postmortem & Design Doc",
        description: "Public writeup of the migration strategy for a zero-downtime ledger cutover.",
        url: "https://example.com/work/ledger-rewrite",
      },
    ],
    links: {
      linkedin: "https://linkedin.com/in/danielkwon",
      github: "https://github.com/dkwon",
      website: undefined,
    },
    accent: "navy",
    pitchCount: 5,
  },
  {
    id: "priya-nair",
    name: "Priya Nair",
    title: "Growth Marketing Lead",
    location: "Remote (GMT+5:30)",
    workStyle: ["remote"],
    yearsExperience: 7,
    headline: "B2B SaaS growth — lifecycle, paid, and the analytics to prove it worked.",
    bio: "I run growth like an engineering problem: instrument first, guess second. I've taken two SaaS products from Series A to Series C, owning everything from paid acquisition to activation email flows.",
    skills: ["Growth Strategy", "SQL", "Lifecycle Marketing", "A/B Testing", "Paid Acquisition", "Amplitude"],
    preferredRoles: ["Head of Growth", "Growth Marketing Lead", "VP Marketing"],
    compMin: 130000,
    compMax: 160000,
    compPeriod: "year",
    availability: "Open to offers",
    openToOffers: true,
    experience: [
      {
        role: "Growth Marketing Lead",
        company: "Sprocket",
        period: "2020 — Present",
        description: "Grew paid pipeline 3.4x while cutting CAC 18% through lifecycle automation.",
      },
      {
        role: "Marketing Manager",
        company: "Ferngrove",
        period: "2017 — 2020",
        description: "Built the first attribution model tying content to closed-won revenue.",
      },
    ],
    portfolio: [
      {
        title: "Sprocket Growth Playbook",
        description: "The lifecycle framework used to take activation rate from 24% to 51%.",
        url: "https://example.com/work/sprocket-playbook",
      },
    ],
    links: {
      linkedin: "https://linkedin.com/in/priyanair",
      website: "https://priyanair.co",
    },
    accent: "forest",
    pitchCount: 2,
  },
  {
    id: "marcus-bell",
    name: "Marcus Bell",
    title: "Full-Stack Engineer",
    location: "Chicago, IL",
    workStyle: ["hybrid", "onsite"],
    yearsExperience: 4,
    headline: "React and Node generalist who ships. Early-stage startup experience.",
    bio: "I've been employee #4 twice. I'm fast, I'm comfortable with ambiguity, and I'd rather ship something imperfect on Tuesday than something perfect never. Looking for a team where I can own a full surface area again.",
    skills: ["React", "TypeScript", "Node.js", "PostgreSQL", "Next.js", "Tailwind CSS"],
    preferredRoles: ["Full-Stack Engineer", "Founding Engineer", "Frontend Engineer"],
    compMin: 115000,
    compMax: 140000,
    compPeriod: "year",
    availability: "Available immediately",
    openToOffers: true,
    experience: [
      {
        role: "Founding Engineer",
        company: "Hearthside",
        period: "2022 — Present",
        description: "Built the product from zero to first 500 paying customers, alone for the first 8 months.",
      },
      {
        role: "Software Engineer",
        company: "Dropwell",
        period: "2020 — 2022",
        description: "Owned the customer-facing dashboard; migrated the app from Rails views to a React SPA.",
      },
    ],
    portfolio: [
      {
        title: "Hearthside",
        description: "Live product — booking and CRM tooling for independent contractors.",
        url: "https://example.com/work/hearthside",
      },
    ],
    links: {
      linkedin: "https://linkedin.com/in/marcusbell",
      github: "https://github.com/marcusbell",
    },
    accent: "clay",
    pitchCount: 4,
  },
  {
    id: "sofia-reyes",
    name: "Sofia Reyes",
    title: "Data Scientist",
    location: "Madrid, Spain",
    workStyle: ["remote", "hybrid"],
    yearsExperience: 6,
    headline: "ML for fraud and risk. I ship models that go to production, not notebooks.",
    bio: "I work at the boundary of data science and engineering — models are only useful if they run in production under load. I've built fraud detection systems processing 40M events a day and I care a lot about interpretability for the humans downstream of my models.",
    skills: ["Python", "PyTorch", "SQL", "MLOps", "Feature Engineering", "Airflow"],
    preferredRoles: ["Senior Data Scientist", "ML Engineer", "Applied Scientist"],
    compMin: 120000,
    compMax: 150000,
    compPeriod: "year",
    availability: "Available in 4 weeks",
    openToOffers: true,
    experience: [
      {
        role: "Data Scientist",
        company: "Cabra Risk",
        period: "2021 — Present",
        description: "Built the fraud model suite protecting $600M in annual transaction volume.",
      },
      {
        role: "Data Analyst",
        company: "Vento Retail",
        period: "2019 — 2021",
        description: "Built demand forecasting models that cut overstock by 14%.",
      },
    ],
    portfolio: [
      {
        title: "Real-Time Fraud Scoring",
        description: "Architecture writeup for a sub-100ms fraud scoring pipeline.",
        url: "https://example.com/work/fraud-scoring",
      },
    ],
    links: {
      linkedin: "https://linkedin.com/in/sofiareyes",
      github: "https://github.com/sreyes",
    },
    accent: "slate",
    pitchCount: 1,
  },
  {
    id: "jordan-webb",
    name: "Jordan Webb",
    title: "DevOps / Platform Engineer",
    location: "Remote (US)",
    workStyle: ["remote"],
    yearsExperience: 9,
    headline: "Kubernetes, CI/CD, and making on-call boring again.",
    bio: "I've spent the last two roles turning fragile, tribal-knowledge infra into something a new hire can operate in week one. If your team dreads deploys, that's the kind of problem I want.",
    skills: ["Kubernetes", "Terraform", "AWS", "CI/CD", "Observability", "Go"],
    preferredRoles: ["Platform Engineer", "DevOps Lead", "SRE"],
    compMin: 155000,
    compMax: 185000,
    compPeriod: "year",
    availability: "Available in 2 weeks",
    openToOffers: true,
    experience: [
      {
        role: "Platform Engineering Lead",
        company: "Circuit Health",
        period: "2020 — Present",
        description: "Cut deploy time from 40 minutes to 4; built the on-call rotation and runbook system.",
      },
      {
        role: "DevOps Engineer",
        company: "Anvil Cloud",
        period: "2017 — 2020",
        description: "Migrated the platform from EC2 to Kubernetes with zero customer-facing downtime.",
      },
    ],
    portfolio: [
      {
        title: "Deploy Pipeline Redesign",
        description: "How we went from 40-minute deploys to 4, and made rollback a one-click action.",
        url: "https://example.com/work/deploy-pipeline",
      },
    ],
    links: {
      linkedin: "https://linkedin.com/in/jordanwebb",
      github: "https://github.com/jwebb",
    },
    accent: "plum",
    pitchCount: 2,
  },
  {
    id: "elena-vasquez",
    name: "Elena Vasquez",
    title: "Product Manager",
    location: "New York, NY",
    workStyle: ["hybrid"],
    yearsExperience: 5,
    headline: "PM for developer tools. I write specs engineers actually read.",
    bio: "I came up as an engineer before moving into product, so I still write specs that respect the reader's time. I've launched three developer-facing products and I'm most energized by 0→1 work with a technical user base.",
    skills: ["Product Strategy", "SQL", "User Research", "Roadmapping", "API Design", "Figma"],
    preferredRoles: ["Product Manager", "Senior PM", "Group PM"],
    compMin: 135000,
    compMax: 165000,
    compPeriod: "year",
    availability: "Available in 3 weeks",
    openToOffers: false,
    experience: [
      {
        role: "Senior Product Manager",
        company: "Hookline",
        period: "2022 — Present",
        description: "Launched the public API platform now used by 1,200 developer accounts.",
      },
      {
        role: "Product Manager",
        company: "Basil",
        period: "2020 — 2022",
        description: "Owned the onboarding funnel; activation rate up from 31% to 58%.",
      },
    ],
    portfolio: [
      {
        title: "Hookline API Platform",
        description: "Case study on scoping and launching a public developer API from scratch.",
        url: "https://example.com/work/hookline-api",
      },
    ],
    links: {
      linkedin: "https://linkedin.com/in/elenavasquez",
    },
    accent: "amber",
    pitchCount: 3,
  },
  {
    id: "tomás-ferreira",
    name: "Tomás Ferreira",
    title: "Mobile Engineer (iOS)",
    location: "Lisbon, Portugal",
    workStyle: ["remote", "onsite"],
    yearsExperience: 6,
    headline: "Native iOS at scale — Swift, performance, and App Store craft.",
    bio: "I've shipped apps with 2M+ MAU and I obsess over the small stuff — cold start time, animation timing, the feel of a scroll. I want to join a team that still thinks native quality matters.",
    skills: ["Swift", "SwiftUI", "iOS", "Combine", "Performance Profiling", "CI/CD"],
    preferredRoles: ["Senior iOS Engineer", "Mobile Lead"],
    compMin: 95000,
    compMax: 120000,
    compPeriod: "year",
    availability: "Available in 4 weeks",
    openToOffers: true,
    experience: [
      {
        role: "Senior iOS Engineer",
        company: "Ferro",
        period: "2021 — Present",
        description: "Cut cold-start time by 60% and led the migration to SwiftUI.",
      },
      {
        role: "iOS Engineer",
        company: "Pastelaria Labs",
        period: "2019 — 2021",
        description: "Built the offline-first sync engine for a 1M+ MAU consumer app.",
      },
    ],
    portfolio: [
      {
        title: "Offline Sync Engine",
        description: "How we built conflict-free offline sync for a consumer app at scale.",
        url: "https://example.com/work/offline-sync",
      },
    ],
    links: {
      linkedin: "https://linkedin.com/in/tomasferreira",
      github: "https://github.com/tferreira",
    },
    accent: "navy",
    pitchCount: 1,
  },
  {
    id: "grace-okafor",
    name: "Grace Okafor",
    title: "Engineering Manager",
    location: "London, UK",
    workStyle: ["hybrid", "remote"],
    yearsExperience: 10,
    headline: "First-time-manager mentor, second-time EM. I build teams that stay.",
    bio: "I manage eight engineers across two squads and my retention rate speaks for itself — one departure in three years, and that was a relocation. I care about clear leveling, honest feedback, and protecting my team's focus time.",
    skills: ["Engineering Management", "System Design", "Hiring", "Mentorship", "TypeScript", "Roadmapping"],
    preferredRoles: ["Engineering Manager", "Director of Engineering"],
    compMin: 150000,
    compMax: 180000,
    compPeriod: "year",
    availability: "Open to offers",
    openToOffers: true,
    experience: [
      {
        role: "Engineering Manager",
        company: "Kindred Labs",
        period: "2021 — Present",
        description: "Grew the team from 3 to 8; built the leveling framework now used company-wide.",
      },
      {
        role: "Senior Software Engineer",
        company: "Almanac",
        period: "2017 — 2021",
        description: "Tech lead for the collaboration engine; moved into management in year 3.",
      },
    ],
    portfolio: [
      {
        title: "Kindred Leveling Framework",
        description: "A public writeup of the engineering leveling rubric adopted org-wide.",
        url: "https://example.com/work/kindred-leveling",
      },
    ],
    links: {
      linkedin: "https://linkedin.com/in/graceokafor",
    },
    accent: "forest",
    pitchCount: 2,
  },
];

export const pitches: Pitch[] = [
  {
    id: "pitch-1",
    candidateId: "amara-osei",
    companyName: "Northlight Financial",
    companyBlurb: "Series C fintech, 210 employees, building banking infrastructure for small businesses.",
    jobTitle: "Design Lead, Core Product",
    compMin: 160000,
    compMax: 185000,
    compPeriod: "year",
    workStyle: "hybrid",
    responsibilities: [
      "Own design direction for our core banking product used by 40,000 small businesses",
      "Build out and lead a team of 3 product designers",
      "Partner directly with the VP of Product on roadmap and design reviews",
    ],
    whySelected: "Your work on Ledgerline's design system is exactly the kind of systems thinking we need — we're at the point where our product has outgrown ad-hoc design decisions.",
    whyJoin: "You'd have real authority over design direction, not just execution — we're hiring a lead, not a fourth designer. Our last design lead was promoted to VP of Product within two years.",
    interviewStages: ["Intro call (30 min)", "Portfolio review", "Design exercise (paid, 3 hrs)", "Team panel", "Founder chat"],
    aiInterviews: false,
    hiringTimeline: "Looking to close within 3 weeks",
    benefits: ["Full health/dental/vision", "$2,500 annual learning budget", "Equity: 0.15%–0.3%", "Unlimited PTO"],
    equity: "0.15%–0.3%",
    status: "pending",
    sentAt: "2026-08-14",
  },
  {
    id: "pitch-2",
    candidateId: "amara-osei",
    companyName: "Fieldstone",
    companyBlurb: "Seed-stage B2B marketplace connecting contractors with commercial property managers.",
    jobTitle: "Founding Product Designer",
    compMin: 130000,
    compMax: 150000,
    compPeriod: "year",
    workStyle: "remote",
    responsibilities: [
      "Design the entire product experience from a near-blank slate",
      "Run user research directly with contractors and property managers",
      "Establish design foundations before we scale the team",
    ],
    whySelected: "We watched your Wayfare checkout case study in our team meeting. That's the exact conversion problem we have right now.",
    whyJoin: "True 0→1 ownership and founder-level equity. You'd be designer #1, reporting directly to the CEO.",
    interviewStages: ["Founder call", "Working session (paid)", "Reference calls"],
    aiInterviews: false,
    hiringTimeline: "Flexible — we're being selective, not fast",
    benefits: ["Health coverage", "Equity: 0.5%–1.0%", "Home office stipend"],
    equity: "0.5%–1.0%",
    status: "interested",
    sentAt: "2026-08-10",
  },
  {
    id: "pitch-3",
    candidateId: "amara-osei",
    companyName: "Vantage Robotics",
    companyBlurb: "Series B industrial robotics company building warehouse automation.",
    jobTitle: "Senior Product Designer, Fleet Ops",
    compMin: 150000,
    compMax: 170000,
    compPeriod: "year",
    workStyle: "onsite",
    responsibilities: [
      "Design the operator-facing console for warehouse fleet management",
      "Translate complex robotics telemetry into usable interfaces",
      "Collaborate closely with our robotics and controls engineers",
    ],
    whySelected: "We need someone who's designed for trust and clarity under real stakes — your fintech background maps directly to our safety-critical interfaces.",
    whyJoin: "This is genuinely novel design work — there's no Dribbble shot to copy for warehouse robot fleet ops. You'd be defining the category.",
    interviewStages: ["Recruiter screen", "Hiring manager chat", "Design challenge", "Onsite (half day)"],
    aiInterviews: true,
    hiringTimeline: "4–6 weeks",
    benefits: ["Full health/dental/vision", "401(k) match", "Equity", "Relocation assistance"],
    status: "maybe",
    sentAt: "2026-08-05",
  },
  {
    id: "pitch-4",
    candidateId: "daniel-kwon",
    companyName: "Meridian Systems",
    companyBlurb: "Series D infrastructure company; payments and ledger tooling for other fintechs.",
    jobTitle: "Principal Engineer, Ledger Platform",
    compMin: 210000,
    compMax: 245000,
    compPeriod: "year",
    workStyle: "remote",
    responsibilities: [
      "Set technical direction for our ledger and reconciliation platform",
      "Mentor a team of 12 engineers across 3 pods",
      "Own the architecture for our next-gen multi-currency ledger",
    ],
    whySelected: "Your Northbeam ledger rewrite postmortem is required reading on our team already. We need someone who's actually done this, not read about it.",
    whyJoin: "This is the hardest version of the problem you already solved — multi-currency, multi-tenant, at 5x your previous scale. Plus a technical staff+ track with no forced move into management.",
    interviewStages: ["Recruiter call", "Systems design (90 min)", "Pairing session", "Panel with 3 principals", "Leadership chat"],
    aiInterviews: false,
    hiringTimeline: "Targeting an offer within 4 weeks",
    benefits: ["Full health/dental/vision", "$5,000 learning budget", "Equity refreshers", "4-day work week"],
    status: "pending",
    sentAt: "2026-08-16",
  },
  {
    id: "pitch-5",
    candidateId: "daniel-kwon",
    companyName: "Cascade Logistics",
    companyBlurb: "Series C supply chain platform, 340 employees.",
    jobTitle: "Staff Backend Engineer, Platform",
    compMin: 195000,
    compMax: 215000,
    compPeriod: "year",
    workStyle: "hybrid",
    responsibilities: [
      "Lead the redesign of our event-driven order processing pipeline",
      "Set standards for service ownership across 40+ microservices",
      "Partner with SRE on reliability targets",
    ],
    whySelected: "Your background in distributed systems and Kafka is a near-exact match to the reliability problems we're facing at our current scale.",
    whyJoin: "You'd inherit a real, gnarly scaling problem — not a greenfield rebuild — with a team that's already bought into fixing it right.",
    interviewStages: ["Recruiter screen", "Technical phone screen", "Onsite loop (4 interviews)", "Offer discussion"],
    aiInterviews: false,
    hiringTimeline: "6–8 weeks",
    benefits: ["Health coverage", "401(k) match", "Equity", "Remote stipend"],
    status: "passed",
    sentAt: "2026-07-28",
  },
  {
    id: "pitch-6",
    candidateId: "daniel-kwon",
    companyName: "Halcyon Data",
    companyBlurb: "Seed-stage observability startup founded by ex-Datadog engineers.",
    jobTitle: "Founding Backend Engineer",
    compMin: 175000,
    compMax: 200000,
    compPeriod: "year",
    workStyle: "remote",
    responsibilities: [
      "Design our time-series storage engine from scratch",
      "Be one of the first 5 engineering hires",
      "Shape engineering culture and hiring bar",
    ],
    whySelected: "We need someone who's built systems that can't be wrong — your payments background is a strong signal for the correctness bar we're holding ourselves to.",
    whyJoin: "Meaningful equity, small team, and a technical problem (time-series at scale) that's genuinely fun to work on.",
    interviewStages: ["Founder call", "Technical deep dive", "Trial project (paid, async)"],
    aiInterviews: false,
    hiringTimeline: "Moving fast — aiming for 2 weeks",
    benefits: ["Health coverage", "Equity: 0.4%–0.8%", "Flexible hours"],
    equity: "0.4%–0.8%",
    status: "pending",
    sentAt: "2026-08-17",
  },
  {
    id: "pitch-7",
    candidateId: "marcus-bell",
    companyName: "Ridgeway",
    companyBlurb: "Seed-stage vertical SaaS for independent veterinary clinics.",
    jobTitle: "Founding Engineer",
    compMin: 125000,
    compMax: 145000,
    compPeriod: "year",
    workStyle: "remote",
    responsibilities: [
      "Own the full stack for our clinic management product",
      "Ship directly to production multiple times a week",
      "Talk to customers alongside the founders",
    ],
    whySelected: "Hearthside is almost exactly our stage and shape — you've already done the thing we're asking you to do here.",
    whyJoin: "Real ownership from day one, meaningful equity, and a founding team that ships instead of debating in Figma for three weeks.",
    interviewStages: ["Founder call", "Take-home (4 hrs, paid)", "Pairing session"],
    aiInterviews: false,
    hiringTimeline: "1–2 weeks",
    benefits: ["Health coverage", "Equity: 0.75%–1.5%", "Fully remote"],
    equity: "0.75%–1.5%",
    status: "interested",
    sentAt: "2026-08-15",
  },
  {
    id: "pitch-8",
    candidateId: "marcus-bell",
    companyName: "Bellwood Retail",
    companyBlurb: "Series B commerce platform for independent retailers.",
    jobTitle: "Full-Stack Engineer",
    compMin: 120000,
    compMax: 135000,
    compPeriod: "year",
    workStyle: "hybrid",
    responsibilities: [
      "Build inventory sync features across our POS integrations",
      "Own a full vertical slice from API to UI",
      "Rotate through on-call every 6 weeks",
    ],
    whySelected: "Your React and Node experience lines up cleanly with our stack, and we liked that you've shipped in ambiguous, early-stage environments.",
    whyJoin: "Established product-market fit with startup-speed shipping — less risk than pre-seed, more ownership than a big company.",
    interviewStages: ["Recruiter screen", "Technical screen", "Onsite (3 interviews)"],
    aiInterviews: true,
    hiringTimeline: "3–4 weeks",
    benefits: ["Full health/dental/vision", "401(k) match", "Equity", "Hybrid — 2 days/week"],
    status: "pending",
    sentAt: "2026-08-12",
  },
  {
    id: "pitch-9",
    candidateId: "priya-nair",
    companyName: "Loomwork",
    companyBlurb: "Series B project management SaaS for creative agencies.",
    jobTitle: "Head of Growth",
    compMin: 140000,
    compMax: 165000,
    compPeriod: "year",
    workStyle: "remote",
    responsibilities: [
      "Build and lead our first dedicated growth function",
      "Own the paid acquisition budget and lifecycle strategy",
      "Report directly to the CMO",
    ],
    whySelected: "The Sprocket playbook you published is the clearest lifecycle marketing writeup we've read this year — we want that thinking applied here.",
    whyJoin: "You'd build the growth function from scratch with real budget and executive support, not inherit someone else's half-finished strategy.",
    interviewStages: ["Recruiter call", "Strategy presentation", "Panel with CMO + CEO"],
    aiInterviews: false,
    hiringTimeline: "4 weeks",
    benefits: ["Health coverage", "Equity", "$1,500 learning budget", "Fully remote"],
    status: "maybe",
    sentAt: "2026-08-09",
  },
  {
    id: "pitch-10",
    candidateId: "grace-okafor",
    companyName: "Almere",
    companyBlurb: "Series C climate tech company, 180 employees.",
    jobTitle: "Director of Engineering",
    compMin: 175000,
    compMax: 205000,
    compPeriod: "year",
    workStyle: "hybrid",
    responsibilities: [
      "Lead 3 engineering managers and ~20 engineers",
      "Own technical strategy alongside the VP of Engineering",
      "Rebuild our leveling and promotion framework",
    ],
    whySelected: "The leveling framework you published at Kindred is exactly the kind of clear, fair system we're missing — and your retention numbers speak for themselves.",
    whyJoin: "A genuine step up in scope, with a VP who wants a strong partner rather than someone to manage from above.",
    interviewStages: ["Recruiter call", "VP of Eng conversation", "Skip-level panel", "Leadership presentation"],
    aiInterviews: false,
    hiringTimeline: "6 weeks",
    benefits: ["Full health/dental/vision", "Equity", "$3,000 learning budget", "4 weeks PTO minimum"],
    status: "pending",
    sentAt: "2026-08-11",
  },
  {
    id: "pitch-11",
    candidateId: "daniel-kwon",
    companyName: "Northlight Financial",
    companyBlurb: "Series C fintech, 210 employees, building banking infrastructure for small businesses.",
    jobTitle: "Staff Engineer, Payments Platform",
    compMin: 205000,
    compMax: 235000,
    compPeriod: "year",
    workStyle: "hybrid",
    responsibilities: [
      "Own the architecture for our multi-rail payments processing system",
      "Set reliability and correctness standards across the payments org",
      "Mentor senior engineers and review critical system designs",
    ],
    whySelected: "Your ledger rewrite at Northbeam is the closest thing we've seen to the correctness bar our payments team needs to hit.",
    whyJoin: "You'd own a system that's core to the business, with direct access to the VP of Engineering and a real staff-level track.",
    interviewStages: ["Recruiter screen", "Systems design", "Pairing session", "Panel", "Leadership chat"],
    aiInterviews: false,
    hiringTimeline: "3–5 weeks",
    benefits: ["Full health/dental/vision", "$2,500 annual learning budget", "Equity: 0.1%–0.2%", "Unlimited PTO"],
    equity: "0.1%–0.2%",
    status: "interested",
    sentAt: "2026-08-08",
  },
  {
    id: "pitch-12",
    candidateId: "marcus-bell",
    companyName: "Northlight Financial",
    companyBlurb: "Series C fintech, 210 employees, building banking infrastructure for small businesses.",
    jobTitle: "Full-Stack Engineer, Growth Team",
    compMin: 125000,
    compMax: 145000,
    compPeriod: "year",
    workStyle: "hybrid",
    responsibilities: [
      "Build and ship experiments across onboarding and activation",
      "Partner directly with product and design on growth initiatives",
      "Own instrumentation for experiment analysis",
    ],
    whySelected: "You've built full-stack products end to end at an early-stage company — that speed is exactly what our growth team needs.",
    whyJoin: "A high-visibility team with direct executive attention and a fast experiment cadence, backed by the stability of a Series C company.",
    interviewStages: ["Recruiter screen", "Technical screen", "Onsite (3 interviews)"],
    aiInterviews: true,
    hiringTimeline: "3–4 weeks",
    benefits: ["Full health/dental/vision", "401(k) match", "Equity", "Hybrid — 3 days/week"],
    status: "passed",
    sentAt: "2026-07-30",
  },
];

export function getCandidateById(id: string) {
  return candidates.find((c) => c.id === id);
}

export function getPitchesForCandidate(candidateId: string) {
  return pitches.filter((p) => p.candidateId === candidateId);
}

export function getPitchesForCompany(companyName: string) {
  return pitches.filter((p) => p.companyName === companyName);
}
